#!/bin/bash
#shellscript to check if a particular software is installed or not
value=`dpkg -l |awk '{print $2}'|grep -i $1|wc -l`
if [ $value = 0 ]; then
  echo "software is not installed"
else
  echo "software is already installed"
fi