#!/bin/bash
#shellscript to add two numbers supplied as command line arguments. 
#If these two inputs are null or invalid, show error and its usage
firstnumber=$1
secondnumber=$2
re='^[0-9]+$'
if ! [[ $firstnumber =~ $re && $secondnumber =~ $re ]] ; then
   echo "Not a number null or invalid" >&2;
else
  sum=$(expr $firstnumber + $secondnumber)
  echo "sum is" $sum
fi
